name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      # Install monorepo dependencies
    - run: npm ci
      # Install all dependencies and link packages
    - run: lerna bootstrap
      # Build climo
    - run: tsc --build
      working-directory: ./scripts
      # Run test in all packages
    - run: node ./dist/index.js run test *
      working-directory: ./scripts
      
